apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-deployment
  labels:
    app: gocrisp-wordcount
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gocrisp-wordcount
  template:
    metadata:
      labels:
        app: gocrisp-wordcount
    spec:
      containers:
        - name: wordcount
          image: gocrisp-wordcount:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /ping
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3

